// <auto-generated />
using System;
using AuditSentinel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditSentinel.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251212153006_LoginyRegistrosDB")]
    partial class LoginyRegistrosDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditSentinel.Models.Escaneos", b =>
                {
                    b.Property<int>("IdEscaneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscaneo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEscaneo")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEscaneo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEscaneo");

                    b.ToTable("Escaneos");
                });

            modelBuilder.Entity("AuditSentinel.Models.EscaneosPlantillas", b =>
                {
                    b.Property<int>("IdEscaneo")
                        .HasColumnType("int");

                    b.Property<int>("IdPlantilla")
                        .HasColumnType("int");

                    b.HasKey("IdEscaneo", "IdPlantilla");

                    b.HasIndex("IdPlantilla");

                    b.ToTable("EscaneosPlantillas");
                });

            modelBuilder.Entity("AuditSentinel.Models.EscaneosReportes", b =>
                {
                    b.Property<int>("IdEscaneo")
                        .HasColumnType("int");

                    b.Property<int>("IdReporte")
                        .HasColumnType("int");

                    b.HasKey("IdEscaneo", "IdReporte");

                    b.HasIndex("IdReporte");

                    b.ToTable("EscaneosReportes");
                });

            modelBuilder.Entity("AuditSentinel.Models.EscaneosServidores", b =>
                {
                    b.Property<int>("IdEscaneo")
                        .HasColumnType("int");

                    b.Property<int>("IdServidor")
                        .HasColumnType("int");

                    b.HasKey("IdEscaneo", "IdServidor");

                    b.HasIndex("IdServidor");

                    b.ToTable("EscaneosServidores");
                });

            modelBuilder.Entity("AuditSentinel.Models.EscaneosVulnerabilidades", b =>
                {
                    b.Property<int>("IdEscaneo")
                        .HasColumnType("int");

                    b.Property<int>("IdVulnerabilidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEscaneo")
                        .HasColumnType("datetime2");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEscaneo", "IdVulnerabilidad");

                    b.HasIndex("IdVulnerabilidad");

                    b.ToTable("EscaneosVulnerabilidades");
                });

            modelBuilder.Entity("AuditSentinel.Models.Plantillas", b =>
                {
                    b.Property<int>("IdPlantilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlantilla"));

                    b.Property<string>("NombrePlantilla")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdPlantilla");

                    b.ToTable("Plantillas");
                });

            modelBuilder.Entity("AuditSentinel.Models.PlantillasVulnerabilidades", b =>
                {
                    b.Property<int>("IdPlantilla")
                        .HasColumnType("int");

                    b.Property<int>("IdVulnerabilidad")
                        .HasColumnType("int");

                    b.HasKey("IdPlantilla", "IdVulnerabilidad");

                    b.HasIndex("IdVulnerabilidad");

                    b.ToTable("PlantillasVulnerabilidades");
                });

            modelBuilder.Entity("AuditSentinel.Models.Registro", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmacionPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AuditSentinel.Models.Reportes", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreReporte")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("cumplimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReporte");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("AuditSentinel.Models.Servidores", b =>
                {
                    b.Property<int>("IdServidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServidor"));

                    b.Property<DateTime>("Create_is")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("NombreServidor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SistemaOperativo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdServidor");

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("AuditSentinel.Models.Vulnerabilidades", b =>
                {
                    b.Property<int>("IdVulnerabilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVulnerabilidad"));

                    b.Property<string>("Comando")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaDetectada")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreVulnerabilidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResultadoEsperado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdVulnerabilidad");

                    b.ToTable("Vulnerabilidades");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AuditSentinel.Models.EscaneosPlantillas", b =>
                {
                    b.HasOne("AuditSentinel.Models.Escaneos", "Escaneos")
                        .WithMany("EscaneosPlantillas")
                        .HasForeignKey("IdEscaneo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditSentinel.Models.Plantillas", "Plantillas")
                        .WithMany("EscaneosPlantillas")
                        .HasForeignKey("IdPlantilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escaneos");

                    b.Navigation("Plantillas");
                });

            modelBuilder.Entity("AuditSentinel.Models.EscaneosReportes", b =>
                {
                    b.HasOne("AuditSentinel.Models.Escaneos", "Escaneos")
                        .WithMany("EscaneosReportes")
                        .HasForeignKey("IdEscaneo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditSentinel.Models.Reportes", "Reportes")
                        .WithMany("EscaneosReportes")
                        .HasForeignKey("IdReporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escaneos");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("AuditSentinel.Models.EscaneosServidores", b =>
                {
                    b.HasOne("AuditSentinel.Models.Escaneos", "Escaneos")
                        .WithMany("EscaneosServidores")
                        .HasForeignKey("IdEscaneo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditSentinel.Models.Servidores", "Servidores")
                        .WithMany("EscaneosServidores")
                        .HasForeignKey("IdServidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escaneos");

                    b.Navigation("Servidores");
                });

            modelBuilder.Entity("AuditSentinel.Models.EscaneosVulnerabilidades", b =>
                {
                    b.HasOne("AuditSentinel.Models.Escaneos", "Escaneos")
                        .WithMany("EscaneosVulnerabilidades")
                        .HasForeignKey("IdEscaneo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditSentinel.Models.Vulnerabilidades", "Vulnerabilidades")
                        .WithMany("EscaneosVulnerabilidades")
                        .HasForeignKey("IdVulnerabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escaneos");

                    b.Navigation("Vulnerabilidades");
                });

            modelBuilder.Entity("AuditSentinel.Models.PlantillasVulnerabilidades", b =>
                {
                    b.HasOne("AuditSentinel.Models.Plantillas", "Plantillas")
                        .WithMany("PlantillasVulnerabilidades")
                        .HasForeignKey("IdPlantilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditSentinel.Models.Vulnerabilidades", "Vulnerabilidades")
                        .WithMany("PlantillasVulnerabilidades")
                        .HasForeignKey("IdVulnerabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantillas");

                    b.Navigation("Vulnerabilidades");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AuditSentinel.Models.Registro", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AuditSentinel.Models.Registro", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditSentinel.Models.Registro", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AuditSentinel.Models.Registro", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuditSentinel.Models.Escaneos", b =>
                {
                    b.Navigation("EscaneosPlantillas");

                    b.Navigation("EscaneosReportes");

                    b.Navigation("EscaneosServidores");

                    b.Navigation("EscaneosVulnerabilidades");
                });

            modelBuilder.Entity("AuditSentinel.Models.Plantillas", b =>
                {
                    b.Navigation("EscaneosPlantillas");

                    b.Navigation("PlantillasVulnerabilidades");
                });

            modelBuilder.Entity("AuditSentinel.Models.Reportes", b =>
                {
                    b.Navigation("EscaneosReportes");
                });

            modelBuilder.Entity("AuditSentinel.Models.Servidores", b =>
                {
                    b.Navigation("EscaneosServidores");
                });

            modelBuilder.Entity("AuditSentinel.Models.Vulnerabilidades", b =>
                {
                    b.Navigation("EscaneosVulnerabilidades");

                    b.Navigation("PlantillasVulnerabilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
